os: osx
language: generic
before_install:
  - sudo pip2 install pyOpenSSL --upgrade
install:
  - sudo python .scripts/install-unity.py --package Unity 2017.1.1f1
script:
  - .scripts/test $TRAVIS_BUILD_DIR eppz.TestResult.xml
