language: python
python:
  - "3.6"
before_install:
  - python .scripts/install-unity.py --packages
install:  
  - python .scripts/install-unity.py --package Unity 5.6.2f1
script:
  - .scripts/test.command $TRAVIS_BUILD_DIR eppz.TestResult.xml
